# Generated by Django 3.1.5 on 2021-02-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostPassagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(db_index=True, max_length=100, unique=True)),
                ('valeA', models.FloatField(blank=True, max_length=3, null=True)),
                ('valeB', models.FloatField(blank=True, max_length=3, null=True)),
                ('valeC', models.FloatField(blank=True, max_length=3, null=True)),
                ('valeD', models.FloatField(blank=True, max_length=3, null=True)),
                ('valeE', models.FloatField(blank=True, max_length=3, null=True)),
                ('valeF', models.FloatField(blank=True, max_length=3, null=True)),
                ('valeG', models.FloatField(blank=True, max_length=3, null=True)),
                ('imA', models.FloatField(blank=True, max_length=5, null=True, verbose_name='InterMunicipal 10 km')),
                ('imB', models.FloatField(blank=True, max_length=5, null=True, verbose_name='InterMunicipal 30 km')),
                ('imC', models.FloatField(blank=True, max_length=5, null=True, verbose_name='InterMunicipal 50 km')),
                ('imD', models.FloatField(blank=True, max_length=5, null=True, verbose_name='InterMunicipal 70 km')),
                ('imE', models.FloatField(blank=True, max_length=5, null=True, verbose_name='InterMunicipal 90 km')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDOHresults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colaborador', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Promotores')),
                ('produtividade', models.TimeField(verbose_name='Produtividade')),
                ('deslocamento', models.TimeField(verbose_name='Deslocamento')),
                ('ocio', models.TimeField(verbose_name='Ócio')),
                ('hrsnaocontab', models.TimeField(verbose_name='Horas não contabilizadas')),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regionais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontodeVenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PDV', models.CharField(max_length=200, unique=True, verbose_name='Ponto de Venda')),
                ('canal', models.CharField(choices=[('Atacado', 'Atacado'), ('Varejo', 'Varejo')], max_length=10, verbose_name='Canal do PDV')),
                ('macroRegional', models.CharField(choices=[('Nordeste', 'NE'), ('Norte', 'NO'), ('Centro-Oeste', 'CEO'), ('Sudeste', 'SUD'), ('Sul', 'SU')], max_length=50, verbose_name='Macroregional')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('logradouro', models.CharField(max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('CEP', models.CharField(max_length=9)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppdv.bandeira', to_field='nome')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppdv.estados', to_field='sigla', verbose_name='Estado')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppdv.rede', to_field='nome')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppdv.regionais', to_field='nome', verbose_name='Regional')),
            ],
            options={
                'verbose_name': 'Ponto de Venda',
                'verbose_name_plural': 'Pontos de Venda',
            },
        ),
    ]
