# Generated by Django 3.1.5 on 2021-02-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppdv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandeira',
            options={'verbose_name': 'Bandeira', 'verbose_name_plural': 'Bandeiras'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='rede',
            options={'verbose_name': 'Rede', 'verbose_name_plural': 'Redes'},
        ),
        migrations.AlterModelOptions(
            name='regionais',
            options={'verbose_name': 'Regional', 'verbose_name_plural': 'Regionais'},
        ),
    ]
