# Generated by Django 3.1.5 on 2021-02-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppdv', '0002_auto_20210208_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costpassagens',
            options={'verbose_name': 'Mapa de Custo Passagens Transporte publico'},
        ),
    ]
