# Generated by Django 3.1.5 on 2021-02-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppdv', '0003_auto_20210208_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costpassagens',
            options={'verbose_name': 'Mapa de custo de passagens (Transporte publico)'},
        ),
    ]
